name: Testing

on:
  pull_request:
    types: [opened]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 18
      - run: yarn install
      - run: yarn run nx run-many --target=lint --projects=web,api

  format-write:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 18
      - run: yarn install
      - run: yarn run nx format:write

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 18
      - run: yarn install
      - run: yarn run nx run-many --target=build --projects=web,api

  clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 18
      - run: yarn install
      - run: yarn run nx reset
